<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-02-08T07:06:56 GMT-05:00" name="Default suite" finished-at="2022-02-08T07:06:58 GMT-05:00" duration-ms="2151">
    <groups>
    </groups>
    <test started-at="2022-02-08T07:06:56 GMT-05:00" name="Default test" finished-at="2022-02-08T07:06:58 GMT-05:00" duration-ms="2151">
      <class name="TimeOutsExampleInTestNG.DependsOnFails">
        <test-method signature="parents_permission()[pri:0, instance:TimeOutsExampleInTestNG.DependsOnFails@47faa49c]" started-at="2022-02-08T07:06:56 GMT-05:00" name="parents_permission" finished-at="2022-02-08T07:06:58 GMT-05:00" duration-ms="2032" status="FAIL">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method TimeOutsExampleInTestNG.DependsOnFails.parents_permission() didn't finish within the time-out 2000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TimeOutsExampleInTestNG.DependsOnFails.parents_permission() didn't finish within the time-out 2000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- parents_permission -->
        <test-method signature="love_marriage()[pri:0, instance:TimeOutsExampleInTestNG.DependsOnFails@47faa49c]" started-at="2022-02-08T07:06:58 GMT-05:00" name="love_marriage" finished-at="2022-02-08T07:06:58 GMT-05:00" depends-on-methods="TimeOutsExampleInTestNG.DependsOnFails.parents_permission" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- love_marriage -->
      </class> <!-- TimeOutsExampleInTestNG.DependsOnFails -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
